#! /usr/bin/python3
# -*- mode:python; coding:utf-8 -*-
# this script is for invocation from within the source tree

import sys, os.path

# current bootstrapping. need to do better later
appdir = os.path.dirname(sys.argv[0])
sys.path.insert(0,os.path.join(appdir, "core/python"))

import xmg

inifile = os.path.join(appdir, "xmg.ini")
xmg.load_inifile(inifile)

#sys.path.remove(appdir)
sys.path.insert(0, xmg.config['DEFAULT']['XMG_PYTHON_ROOTDIR'])

import xmg.modular_program
# this should use xmg.config
xmg.modular_program.YAPDIR = os.path.abspath(os.path.join(os.path.dirname(sys.argv[0]),"."))

xmg.modular_program.main()
